module.exports = {
  "United Kingdom": 3.4,
  "Albania": 4.7,
  "Algeria": 5.2,
  "Andorra": 4.7,
  "Angola ": 5.2,
  "Anguilla ": 5.2,
  "Antigua and Barbuda": 5.2,
  "Argentina": 5.2,
  "Armenia": 5.2,
  "Aruba": 5.2,
  "Australia": 5.2,
  "Austria": 3.4,
  "Azerbaijan Republic": 5.2,
  "Bahamas": 5.2,
  "Bahrain": 5.2,
  "Barbados ": 5.2,
  "Belgium": 3.4,
  "Belize ": 5.2,
  "Benin": 5.2,
  "Bermuda": 5.2,
  "Bhutan ": 5.2,
  "Bolivia": 5.2,
  "Bosnia and Herzegovina ": 4.7,
  "Botswana ": 5.2,
  "Brazil ": 5.2,
  "Brunei ": 5.2,
  "Bulgaria ": 3.4,
  "Burkina": 5.2,
  "Burundi": 5.2,
  "Cambodia ": 5.2,
  "Canada ": 3.9,
  "Cape Verde ": 5.2,
  "Cayman Islands ": 5.2,
  "Chad ": 5.2,
  "Chile": 5.2,
  "China": 5.2,
  "Colombia ": 5.2,
  "Comoros": 5.2,
  "Cook Islands ": 5.2,
  "Costa Rica ": 5.2,
  "Croatia": 4.7,
  "Cyprus ": 3.4,
  "Czech Republic ": 3.4,
  "Democratic Republic of the Congo ": 5.2,
  "Denmark": 3.4,
  "Djibouti ": 5.2,
  "Dominica ": 5.2,
  "Dominican Republic ": 5.2,
  "Ecuador": 5.2,
  "El Salvador": 5.2,
  "Eritrea": 5.2,
  "Estonia": 3.4,
  "Ethiopia ": 5.2,
  "Falkland Islands ": 5.2,
  "Faroe Islands": 3.8,
  "Fiji ": 5.2,
  "Finland": 3.4,
  "France ": 3.4,
  "French Guiana": 5.2,
  "French Polynesia ": 5.2,
  "Gabon": 5.2,
  "Republic Gambia": 5.2,
  "Germany": 3.4,
  "Gibraltar": 3.4,
  "Greece ": 3.4,
  "Greenland": 3.8,
  "Grenada": 5.2,
  "Guadeloupe ": 3.4,
  "Guatemala": 5.2,
  "Guinea ": 5.2,
  "Guinea Bissau": 5.2,
  "Guyana ": 5.2,
  "Honduras ": 5.2,
  "HongHong ": 5.2,
  "Hungary": 3.4,
  "Iceland": 3.4,
  "India": 5.2,
  "Indonesia": 5.2,
  "Ireland": 3.4,
  "Israel ": 5.2,
  "Italy": 3.4,
  "Jamaica": 5.2,
  "Japan": 5.2,
  "Jordan ": 5.2,
  "Kazakhstan ": 5.2,
  "Kenya": 5.2,
  "Kiribati ": 5.2,
  "Kuwait ": 5.2,
  "Kyrgyzstan ": 5.2,
  "LaosLatvia ": 5.2,
  "Lesotho": 5.2,
  "Liechtenstein": 3.4,
  "Lithuania": 3.4,
  "Luxembourg ": 3.4,
  "Madagascar ": 5.2,
  "Malawi ": 5.2,
  "Malaysia ": 5.2,
  "Maldives ": 5.2,
  "Mali ": 5.2,
  "Malta": 3.4,
  "MarshallIslands": 5.2,
  "Martinique ": 3.4,
  "Mauritania ": 5.2,
  "Mauritius": 5.2,
  "Mayotte": 3.4,
  "Mexico ": 5.2,
  "Micronesia ": 5.2,
  "Mongolia ": 5.2,
  "Montserrat ": 5.2,
  "Morocco": 5.2,
  "Mozambique ": 5.2,
  "Namibia": 5.2,
  "Nauru": 5.2,
  "Nepal": 5.2,
  "Netherlands": 3.4,
  "Antilles ": 5.2,
  "New Caledonia": 5.2,
  "New Zealand": 5.2,
  "Nicaragua": 5.2,
  "Niger": 5.2,
  "Niue ": 5.2,
  "Norfolk Island ": 5.2,
  "Norway ": 3.4,
  "Oman ": 5.2,
  "Palau": 5.2,
  "Panama ": 5.2,
  "Papua New Guinea ": 5.2,
  "Peru ": 5.2,
  "Philippines": 5.2,
  "Pitcairn Islands ": 5.2,
  "Poland ": 3.4,
  "Portugal ": 3.4,
  "Qatar": 5.2,
  "Republic of the Congo": 5.2,
  "Reunion": 3.4,
  "Romania": 3.4,
  "Russia ": 4.7,
  "Rwanda ": 5.2,
  "Saint Kitts and Nevis Anguilla ": 5.2,
  "Saint Pierre and Miquelon": 5.2,
  "Saint Vincent and Grenadines ": 5.2,
  "Samoa": 5.2,
  "San Marino ": 3.4,
  "Saudi Arabia ": 5.2,
  "Senegal": 5.2,
  "Seychelles ": 5.2,
  "Sierra Leone ": 5.2,
  "Singapore": 5.2,
  "Slovakia ": 3.4,
  "Slovenia ": 3.4,
  "Solomon Islands": 5.2,
  "Somalia": 5.2,
  "South Africa ": 5.2,
  "South Korea": 5.2,
  "Spain": 3.4,
  "Sri Lanka": 5.2,
  "St. Helena ": 5.2,
  "St. Lucia": 5.2,
  "Suriname ": 5.2,
  "Svalbard and Jan Mayen  Islands  ": 5.2,
  "Swaziland  ": 5.2,
  "Sweden ": 3.4,
  "Switzerland": 4.7,
  "Taiwan ": 5.2,
  "Tajikistan ": 5.2,
  "Tanzania ": 5.2,
  "Thailand ": 5.2,
  "Togo ": 5.2,
  "Tonga": 5.2,
  "Trinidad and Tobago": 5.2,
  "Tunisia": 5.2,
  "Turkey ": 4.7,
  "Turkmenistan ": 5.2,
  "Turks and Caicos Islands ": 5.2,
  "Tuvalu ": 5.2,
  "Uganda ": 5.2,
  "Ukraine": 4.7,
  "United Arab Emirates ": 5.2,
  "United States": 4.7,
  "Uruguay": 5.2,
  "Vanuatu": 5.2,
  "Vatican City State ": 3.4,
  "Venezuela": 5.2,
  "Vietnam": 5.2,
  "Virgin Islands (British) ": 5.2,
  "Wallis and Futuna Islands": 5.2,
  "Yemen": 5.2,
  "Zambia ": 5.2,
  "Latvia ": 3.4,
  "Czechia": 3.4
};
